class CfgVehicles {
    //CFP Afghanistan Civilians
    CREATE_AGENT(CFP_C_AFG_Civilian_01);
    CREATE_AGENT(CFP_C_AFG_Civilian_02);

    //CFP African Christian Civilians
    CREATE_AGENT(CFP_C_AFRCHRISTIAN_Civ_1_01);
    CREATE_AGENT(CFP_C_AFRCHRISTIAN_Civ_2_01);
    CREATE_AGENT(CFP_C_AFRCHRISTIAN_Civ_3_01);
    CREATE_AGENT(CFP_C_AFRCHRISTIAN_Civ_4_01);
    CREATE_AGENT(CFP_C_AFRCHRISTIAN_Civ_5_01);
    CREATE_AGENT(CFP_C_AFRCHRISTIAN_Civ_6_01);
    CREATE_AGENT(CFP_C_AFRCHRISTIAN_Civ_7_01);
    CREATE_AGENT(CFP_C_AFRCHRISTIAN_Civ_8_01);
    CREATE_AGENT(CFP_C_AFRCHRISTIAN_Civ_9_01);
    CREATE_AGENT(CFP_C_AFRCHRISTIAN_Civ_10_01);
    CREATE_AGENT(CFP_C_AFRCHRISTIAN_Civ_11_01);
    CREATE_AGENT(CFP_C_AFRCHRISTIAN_Civ_12_01);
    CREATE_AGENT(CFP_C_AFRCHRISTIAN_Civ_13_01);
    CREATE_AGENT(CFP_C_AFRCHRISTIAN_Civ_14_01);

    //CFP African Islamic Civilians
    CREATE_AGENT(CFP_C_AFRISLAMIC_Civ_1_01);
    CREATE_AGENT(CFP_C_AFRISLAMIC_Civ_2_01);
    CREATE_AGENT(CFP_C_AFRISLAMIC_Civ_3_01);
    CREATE_AGENT(CFP_C_AFRISLAMIC_Civ_4_01);
    CREATE_AGENT(CFP_C_AFRISLAMIC_Civ_5_01);
    CREATE_AGENT(CFP_C_AFRISLAMIC_Civ_6_01);
    CREATE_AGENT(CFP_C_AFRISLAMIC_Civ_7_01);
    CREATE_AGENT(CFP_C_AFRISLAMIC_Civ_8_01);
    CREATE_AGENT(CFP_C_AFRISLAMIC_Civ_9_01);
    CREATE_AGENT(CFP_C_AFRISLAMIC_Civ_10_01);
    CREATE_AGENT(CFP_C_AFRISLAMIC_Civ_11_01);
    CREATE_AGENT(CFP_C_AFRISLAMIC_Civ_12_01);

    //CFP Asian Civilians
    CREATE_AGENT(CFP_C_ASIA_Civilian_1_01);
    CREATE_AGENT(CFP_C_ASIA_Civilian_2_01);
    CREATE_AGENT(CFP_C_ASIA_Civilian_3_01);
    CREATE_AGENT(CFP_C_ASIA_Civilian_4_01);
    CREATE_AGENT(CFP_C_ASIA_Civilian_5_01);
    CREATE_AGENT(CFP_C_ASIA_Civilian_6_01);
    CREATE_AGENT(CFP_C_ASIA_Civilian_7_01);
    CREATE_AGENT(CFP_C_ASIA_Civilian_8_01);
    CREATE_AGENT(CFP_C_ASIA_Civilian_9_01);
    CREATE_AGENT(CFP_C_ASIA_Civilian_10_01);
    CREATE_AGENT(CFP_C_ASIA_Civilian_11_01);
    CREATE_AGENT(CFP_C_ASIA_Civilian_12_01);

    //CFP Chernarus Winter Civilians
    CREATE_AGENT(CFP_C_CHERNO_WIN_Civilian_01);
    CREATE_AGENT(CFP_C_CHERNO_WIN_Civilian_02);
    CREATE_AGENT(CFP_C_CHERNO_WIN_Civilian_03);

    //CFP Middle East Civilians
    CREATE_AGENT(CFP_C_ME_Civ_1_01);
    CREATE_AGENT(CFP_C_ME_Civ_2_01);
};
