class CfgVehicles {
    //African Desert Civilians
    CREATE_AGENT(UK3CB_ADC_C_CIV_CHR_01);
    CREATE_AGENT(UK3CB_ADC_C_CIV_CHR_02);
    CREATE_AGENT(UK3CB_ADC_C_HUNTER_CHR);
    CREATE_AGENT(UK3CB_ADC_C_CIV_ISL_01);
    CREATE_AGENT(UK3CB_ADC_C_CIT);
    CREATE_AGENT(UK3CB_ADC_C_COACH);
    CREATE_AGENT(UK3CB_ADC_C_PROF);
    CREATE_AGENT(UK3CB_ADC_C_VILL);
    CREATE_AGENT(UK3CB_ADC_C_WOOD);
    CREATE_AGENT(UK3CB_ADC_C_HELIPILOT);
    CREATE_AGENT(UK3CB_ADC_C_PILOT);
    CREATE_AGENT(UK3CB_ADC_C_DOC_CHR);
    CREATE_AGENT(UK3CB_ADC_C_DOC_ISL);
    CREATE_AGENT(UK3CB_ADC_C_FUNC);
    CREATE_AGENT(UK3CB_ADC_C_LABOURER_CHR);
    CREATE_AGENT(UK3CB_ADC_C_LABOURER_ISL);
    CREATE_AGENT(UK3CB_ADC_C_CIV_CHR);
    CREATE_AGENT(UK3CB_ADC_C_CIV_ISL);
    CREATE_AGENT(UK3CB_ADC_C_SPOT_CHR);
    CREATE_AGENT(UK3CB_ADC_C_SPOT_ISL);
    CREATE_AGENT(UK3CB_ADC_C_WORKER);

    //Middle Eastern Civilians
    CREATE_AGENT(UK3CB_MEC_C_CIV_01);
    CREATE_AGENT(UK3CB_MEC_C_CIV_02);
    CREATE_AGENT(UK3CB_MEC_C_HUNTER);
    CREATE_AGENT(UK3CB_MEC_C_CIT);
    CREATE_AGENT(UK3CB_MEC_C_COACH);
    CREATE_AGENT(UK3CB_MEC_C_PROF);
    CREATE_AGENT(UK3CB_MEC_C_FUNC);
    CREATE_AGENT(UK3CB_MEC_C_HELIPILOT);
    CREATE_AGENT(UK3CB_MEC_C_LABOURER);
    CREATE_AGENT(UK3CB_MEC_C_DOC);
    CREATE_AGENT(UK3CB_MEC_C_PILOT);
    CREATE_AGENT(UK3CB_MEC_C_CIV);
    CREATE_AGENT(UK3CB_MEC_C_SPOT);
    CREATE_AGENT(UK3CB_MEC_C_WORKER);

    //Chernarus Civilians
    CREATE_AGENT(UK3CB_CHC_C_ACT);
    CREATE_AGENT(UK3CB_CHC_C_BODYG);
    CREATE_AGENT(UK3CB_CHC_C_CIT);
    CREATE_AGENT(UK3CB_CHC_C_COACH);
    CREATE_AGENT(UK3CB_CHC_C_DOC);
    CREATE_AGENT(UK3CB_CHC_C_FUNC);
    CREATE_AGENT(UK3CB_CHC_C_HIKER);
    CREATE_AGENT(UK3CB_CHC_C_LABOUR);
    CREATE_AGENT(UK3CB_CHC_C_PILOT);
    CREATE_AGENT(UK3CB_CHC_C_POLITIC);
    CREATE_AGENT(UK3CB_CHC_C_PRIEST);
    CREATE_AGENT(UK3CB_CHC_C_PROF);
    CREATE_AGENT(UK3CB_CHC_C_CIV);
    CREATE_AGENT(UK3CB_CHC_C_SPY);
    CREATE_AGENT(UK3CB_CHC_C_VILL);
    CREATE_AGENT(UK3CB_CHC_C_CAN);
    CREATE_AGENT(UK3CB_CHC_C_WOOD);
    CREATE_AGENT(UK3CB_CHC_C_WORKER);

    //Takistan Civilians
    CREATE_AGENT(UK3CB_TKC_C_CIV);
    CREATE_AGENT(UK3CB_TKC_C_DOC);
    CREATE_AGENT(UK3CB_TKC_C_PILOT);
    CREATE_AGENT(UK3CB_TKC_C_SPOT);
    CREATE_AGENT(UK3CB_TKC_C_WORKER);
};
