#define MAJOR 1
#define MINOR 5
#define PATCH 0

// #define VERSION MACROS
#define VERSION MAJOR.MINOR
#define VERSION_AR MAJOR,MINOR,PATCH
#define VERSION_STR MAJOR##.##MINOR##.##PATCH

#define REQUIRED_VERSION 2.20
#define REQUIRED_CBA_VERSION {3,18,4}
#define REQUIRED_ACE_VERSION {3,20,1}
